name: Delete Old CI Builds

on:
  workflow_dispatch:

jobs:
  DeleteOldCiBuilds:
    name: Delete old CI releases
    runs-on: ubuntu-latest
    steps:
    - name: Delete Package Versions
      uses: actions/delete-package-versions@v2.0.1
      with:
        package-name: 'DansWpfComponents'
        min-versions-to-keep: 5
        token: ${{ github.token }}
