name: .NET

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version of the NuGet to publix X.Y.Z. Don't mess it up 😉
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
