name: Reuseable Release NuGet To Private Feed

on:
  workflow_call:

jobs:
  ReleaseNuGetToPrivateFeed:
    name: Release NuGet To Private Feed
    runs-on: ubuntu-latest
    steps:
    - name: Download NuGet artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: NuGet Package Files

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Release NuGet
      run: dotnet nuget push *.nupkg --source https://nuget.pkg.github.com/DanJBower/index.json --api-key ${{ github.token }}
