name: Test Publish Exe

on:
  workflow_dispatch:

jobs:
  PublishExe:
    name: Publish Demo Executable
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get Latest Release
      id: latest_release
      uses: joutvhu/get-release@v1.0.1
      with:
        latest: true
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Generate Version
      id: make_version
      shell: pwsh
      run: .github\utility\SetPassedVersionNumber.ps1 -latest '${{ steps.latest_release.outputs.tag_name }}'

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Make Executable
      run: dotnet publish /p:DebugType=None /p:DebugSymbols=false /p:PublishReadyToRun=true /p:PublishSingleFile=true /p:PublishReadyToRunShowWarnings=true /p:PublishTrimmed=false /p:IncludeNativeLibrariesForSelfExtract=true DansWpfComponents\DansWpfComponents.Demo\DansWpfComponents.Demo.csproj -o . -c release
      env:
        pipelinePackageVersion: ${{ steps.make_version.outputs.pipelinePackageVersion }}
        pipelineAssemblyVersion: ${{ steps.make_version.outputs.pipelineAssemblyVersion }}

    - name: Upload Executable
      uses: actions/upload-artifact@v3.0.0
      with:
        name: Demo
        path: DansWpfComponents.Demo.exe
        if-no-files-found: error
